-- MySQL Script generated by MySQL Workbench
-- dom 29 dez 2019 16:47:23 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema indice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `indice` ;

-- -----------------------------------------------------
-- Schema indice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `indice` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `indice` ;

-- -----------------------------------------------------
-- Table `indice`.`fato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`fato` ;

CREATE TABLE IF NOT EXISTS `indice`.`fato` (
  `fid` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`macrorregiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`macrorregiao` ;

CREATE TABLE IF NOT EXISTS `indice`.`macrorregiao` (
  `cod` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`estado` ;

CREATE TABLE IF NOT EXISTS `indice`.`estado` (
  `cod` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `codmacro` INT(11) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_estado_macro_idx` (`codmacro` ASC) VISIBLE,
  CONSTRAINT `fk_estado_macrorregiao1`
    FOREIGN KEY (`codmacro`)
    REFERENCES `indice`.`macrorregiao` (`cod`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`mesorregiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`mesorregiao` ;

CREATE TABLE IF NOT EXISTS `indice`.`mesorregiao` (
  `cod` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `codestado` INT(11) NOT NULL,
  PRIMARY KEY (`cod`, `codestado`),
  INDEX `fk_meso_estado_idx` (`codestado` ASC) VISIBLE,
  CONSTRAINT `fk_mesorregiao_estado1`
    FOREIGN KEY (`codestado`)
    REFERENCES `indice`.`estado` (`cod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`microrregiao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`microrregiao` ;

CREATE TABLE IF NOT EXISTS `indice`.`microrregiao` (
  `cod` INT(11) NOT NULL,
  `codmeso` INT(11) NOT NULL,
  `codestado` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod`, `codmeso`, `codestado`),
  INDEX `fk_micro_meso_idx` (`codmeso` ASC, `codestado` ASC) VISIBLE,
  CONSTRAINT `fk_microrregiao_mesorregiao1`
    FOREIGN KEY (`codmeso` , `codestado`)
    REFERENCES `indice`.`mesorregiao` (`cod` , `codestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`municipio` ;

CREATE TABLE IF NOT EXISTS `indice`.`municipio` (
  `cod` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `codmicro` INT(11) NOT NULL,
  `codmeso` INT(11) NOT NULL,
  `codestado` INT(11) NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_municipio_micro_idx` (`codmicro` ASC, `codmeso` ASC, `codestado` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_microrregiao1`
    FOREIGN KEY (`codmicro` , `codmeso` , `codestado`)
    REFERENCES `indice`.`microrregiao` (`cod` , `codmeso` , `codestado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`avalia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`avalia` ;

CREATE TABLE IF NOT EXISTS `indice`.`avalia` (
  `codmun` INT(11) NOT NULL,
  `fato_id` INT(11) NOT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`codmun`, `fato_id`),
  INDEX `fk_municipio_has_fato_fato1_idx` (`fato_id` ASC) VISIBLE,
  INDEX `fk_municipio_has_fato_municipio1_idx` (`codmun` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_has_fato_fato1`
    FOREIGN KEY (`fato_id`)
    REFERENCES `indice`.`fato` (`fid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_municipio_has_fato_municipio1`
    FOREIGN KEY (`codmun`)
    REFERENCES `indice`.`municipio` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`indice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`indice` ;

CREATE TABLE IF NOT EXISTS `indice`.`indice` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `indice`.`pondera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indice`.`pondera` ;

CREATE TABLE IF NOT EXISTS `indice`.`pondera` (
  `indice_id` INT(11) NOT NULL,
  `fato_fid` INT(11) NOT NULL,
  `peso` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`indice_id`, `fato_fid`),
  INDEX `fk_indice_has_fato_fato1_idx` (`fato_fid` ASC) VISIBLE,
  INDEX `fk_indice_has_fato_indice1_idx` (`indice_id` ASC) VISIBLE,
  CONSTRAINT `fk_indice_has_fato_fato1`
    FOREIGN KEY (`fato_fid`)
    REFERENCES `indice`.`fato` (`fid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_indice_has_fato_indice1`
    FOREIGN KEY (`indice_id`)
    REFERENCES `indice`.`indice` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
