insert into estado (codmacro, cod, nome) values ('1','11',"Rondônia");
insert into estado (codmacro, cod, nome) values ('1','12',"Acre");
insert into estado (codmacro, cod, nome) values ('1','13',"Amazonas");
insert into estado (codmacro, cod, nome) values ('1','14',"Roraima");
insert into estado (codmacro, cod, nome) values ('1','15',"Pará");
insert into estado (codmacro, cod, nome) values ('1','16',"Amapá");
insert into estado (codmacro, cod, nome) values ('1','17',"Tocantins");
insert into estado (codmacro, cod, nome) values ('2','21',"Maranhão");
insert into estado (codmacro, cod, nome) values ('2','22',"Piauí");
insert into estado (codmacro, cod, nome) values ('2','23',"Ceará");
insert into estado (codmacro, cod, nome) values ('2','24',"Rio Grande do Norte");
insert into estado (codmacro, cod, nome) values ('2','25',"Paraíba");
insert into estado (codmacro, cod, nome) values ('2','26',"Pernambuco");
insert into estado (codmacro, cod, nome) values ('2','27',"Alagoas");
insert into estado (codmacro, cod, nome) values ('2','28',"Sergipe");
insert into estado (codmacro, cod, nome) values ('2','29',"Bahia");
insert into estado (codmacro, cod, nome) values ('3','31',"Minas Gerais");
insert into estado (codmacro, cod, nome) values ('3','32',"Espírito Santo");
insert into estado (codmacro, cod, nome) values ('3','33',"Rio de Janeiro");
insert into estado (codmacro, cod, nome) values ('3','35',"São Paulo");
insert into estado (codmacro, cod, nome) values ('4','41',"Paraná");
insert into estado (codmacro, cod, nome) values ('4','42',"Santa Catarina");
insert into estado (codmacro, cod, nome) values ('4','43',"Rio Grande do Sul");
insert into estado (codmacro, cod, nome) values ('5','50',"Mato Grosso do Sul");
insert into estado (codmacro, cod, nome) values ('5','51',"Mato Grosso");
insert into estado (codmacro, cod, nome) values ('5','52',"Goiás");
insert into estado (codmacro, cod, nome) values ('5','53',"Distrito Federal");
