insert into mesorregiao (codestado, cod, nome) values ('11','01','Madeira-Guaporé');
insert into mesorregiao (codestado, cod, nome) values ('11','02','Leste Rondoniense');
insert into mesorregiao (codestado, cod, nome) values ('12','01','Vale do Juruá');
insert into mesorregiao (codestado, cod, nome) values ('12','02','Vale do Acre');
insert into mesorregiao (codestado, cod, nome) values ('13','01','Norte Amazonense');
insert into mesorregiao (codestado, cod, nome) values ('13','02','Sudoeste Amazonense');
insert into mesorregiao (codestado, cod, nome) values ('13','03','Centro Amazonense');
insert into mesorregiao (codestado, cod, nome) values ('13','04','Sul Amazonense');
insert into mesorregiao (codestado, cod, nome) values ('14','01','Norte de Roraima');
insert into mesorregiao (codestado, cod, nome) values ('14','02','Sul de Roraima');
insert into mesorregiao (codestado, cod, nome) values ('15','01','Baixo Amazonas');
insert into mesorregiao (codestado, cod, nome) values ('15','02','Marajó');
insert into mesorregiao (codestado, cod, nome) values ('15','03','Metropolitana de Belém');
insert into mesorregiao (codestado, cod, nome) values ('15','04','Nordeste Paraense');
insert into mesorregiao (codestado, cod, nome) values ('15','05','Sudoeste Paraense');
insert into mesorregiao (codestado, cod, nome) values ('15','06','Sudeste Paraense');
insert into mesorregiao (codestado, cod, nome) values ('16','01','Norte do Amapá');
insert into mesorregiao (codestado, cod, nome) values ('16','02','Sul do Amapá');
insert into mesorregiao (codestado, cod, nome) values ('17','01','Ocidental do Tocantins');
insert into mesorregiao (codestado, cod, nome) values ('17','02','Oriental do Tocantins');
insert into mesorregiao (codestado, cod, nome) values ('21','01','Norte Maranhense');
insert into mesorregiao (codestado, cod, nome) values ('21','02','Oeste Maranhense');
insert into mesorregiao (codestado, cod, nome) values ('21','03','Centro Maranhense');
insert into mesorregiao (codestado, cod, nome) values ('21','04','Leste Maranhense');
insert into mesorregiao (codestado, cod, nome) values ('21','05','Sul Maranhense');
insert into mesorregiao (codestado, cod, nome) values ('22','01','Norte Piauiense');
insert into mesorregiao (codestado, cod, nome) values ('22','02','Centro-Norte Piauiense');
insert into mesorregiao (codestado, cod, nome) values ('22','03','Sudoeste Piauiense');
insert into mesorregiao (codestado, cod, nome) values ('22','04','Sudeste Piauiense');
insert into mesorregiao (codestado, cod, nome) values ('23','01','Noroeste Cearense');
insert into mesorregiao (codestado, cod, nome) values ('23','02','Norte Cearense');
insert into mesorregiao (codestado, cod, nome) values ('23','03','Metropolitana de Fortaleza');
insert into mesorregiao (codestado, cod, nome) values ('23','04','Sertões Cearenses');
insert into mesorregiao (codestado, cod, nome) values ('23','05','Jaguaribe');
insert into mesorregiao (codestado, cod, nome) values ('23','06','Centro-Sul Cearense');
insert into mesorregiao (codestado, cod, nome) values ('23','07','Sul Cearense');
insert into mesorregiao (codestado, cod, nome) values ('24','01','Oeste Potiguar');
insert into mesorregiao (codestado, cod, nome) values ('24','02','Central Potiguar');
insert into mesorregiao (codestado, cod, nome) values ('24','03','Agreste Potiguar');
insert into mesorregiao (codestado, cod, nome) values ('24','04','Leste Potiguar');
insert into mesorregiao (codestado, cod, nome) values ('25','01','Sertão Paraibano');
insert into mesorregiao (codestado, cod, nome) values ('25','02','Borborema');
insert into mesorregiao (codestado, cod, nome) values ('25','03','Agreste Paraibano');
insert into mesorregiao (codestado, cod, nome) values ('25','04','Mata Paraibana');
insert into mesorregiao (codestado, cod, nome) values ('26','01','Sertão Pernambucano');
insert into mesorregiao (codestado, cod, nome) values ('26','02','São Francisco Pernambucano');
insert into mesorregiao (codestado, cod, nome) values ('26','03','Agreste Pernambucano');
insert into mesorregiao (codestado, cod, nome) values ('26','04','Mata Pernambucana');
insert into mesorregiao (codestado, cod, nome) values ('26','05','Metropolitana de Recife');
insert into mesorregiao (codestado, cod, nome) values ('27','01','Sertão Alagoano');
insert into mesorregiao (codestado, cod, nome) values ('27','02','Agreste Alagoano');
insert into mesorregiao (codestado, cod, nome) values ('27','03','Leste Alagoano');
insert into mesorregiao (codestado, cod, nome) values ('28','01','Sertão Sergipano');
insert into mesorregiao (codestado, cod, nome) values ('28','02','Agreste Sergipano');
insert into mesorregiao (codestado, cod, nome) values ('28','03','Leste Sergipano');
insert into mesorregiao (codestado, cod, nome) values ('29','01','Extremo Oeste Baiano');
insert into mesorregiao (codestado, cod, nome) values ('29','02','Vale São-Franciscano da Bahia');
insert into mesorregiao (codestado, cod, nome) values ('29','03','Centro Norte Baiano');
insert into mesorregiao (codestado, cod, nome) values ('29','04','Nordeste Baiano');
insert into mesorregiao (codestado, cod, nome) values ('29','05','Metropolitana de Salvador');
insert into mesorregiao (codestado, cod, nome) values ('29','06','Centro Sul Baiano');
insert into mesorregiao (codestado, cod, nome) values ('29','07','Sul Baiano');
insert into mesorregiao (codestado, cod, nome) values ('31','01','Noroeste de Minas');
insert into mesorregiao (codestado, cod, nome) values ('31','02','Norte de Minas');
insert into mesorregiao (codestado, cod, nome) values ('31','03','Jequitinhonha');
insert into mesorregiao (codestado, cod, nome) values ('31','04','Vale do Mucuri');
insert into mesorregiao (codestado, cod, nome) values ('31','05','Triângulo Mineiro/Alto Paranaíba');
insert into mesorregiao (codestado, cod, nome) values ('31','06','Central Mineira');
insert into mesorregiao (codestado, cod, nome) values ('31','07','Metropolitana de Belo Horizonte');
insert into mesorregiao (codestado, cod, nome) values ('31','08','Vale do Rio Doce');
insert into mesorregiao (codestado, cod, nome) values ('31','09','Oeste de Minas');
insert into mesorregiao (codestado, cod, nome) values ('31','10','Sul/Sudoeste de Minas');
insert into mesorregiao (codestado, cod, nome) values ('31','11','Campo das Vertentes');
insert into mesorregiao (codestado, cod, nome) values ('31','12','Zona da Mata');
insert into mesorregiao (codestado, cod, nome) values ('32','01','Noroeste Espírito-santense');
insert into mesorregiao (codestado, cod, nome) values ('32','02','Litoral Norte Espírito-santense');
insert into mesorregiao (codestado, cod, nome) values ('32','03','Central Espírito-santense');
insert into mesorregiao (codestado, cod, nome) values ('32','04','Sul Espírito-santense');
insert into mesorregiao (codestado, cod, nome) values ('33','01','Noroeste Fluminense');
insert into mesorregiao (codestado, cod, nome) values ('33','02','Norte Fluminense');
insert into mesorregiao (codestado, cod, nome) values ('33','03','Centro Fluminense');
insert into mesorregiao (codestado, cod, nome) values ('33','04','Baixadas');
insert into mesorregiao (codestado, cod, nome) values ('33','05','Sul Fluminense');
insert into mesorregiao (codestado, cod, nome) values ('33','06','Metropolitana do Rio de Janeiro');
insert into mesorregiao (codestado, cod, nome) values ('35','01','São José do Rio Preto');
insert into mesorregiao (codestado, cod, nome) values ('35','02','Ribeirão Preto');
insert into mesorregiao (codestado, cod, nome) values ('35','03','Araçatuba');
insert into mesorregiao (codestado, cod, nome) values ('35','04','Bauru');
insert into mesorregiao (codestado, cod, nome) values ('35','05','Araraquara');
insert into mesorregiao (codestado, cod, nome) values ('35','06','Piracicaba');
insert into mesorregiao (codestado, cod, nome) values ('35','07','Campinas');
insert into mesorregiao (codestado, cod, nome) values ('35','08','Presidente Prudente');
insert into mesorregiao (codestado, cod, nome) values ('35','09','Marília');
insert into mesorregiao (codestado, cod, nome) values ('35','10','Assis');
insert into mesorregiao (codestado, cod, nome) values ('35','11','Itapetininga');
insert into mesorregiao (codestado, cod, nome) values ('35','12','Macro Metropolitana Paulista');
insert into mesorregiao (codestado, cod, nome) values ('35','13','Vale do Paraíba Paulista');
insert into mesorregiao (codestado, cod, nome) values ('35','14','Litoral Sul Paulista');
insert into mesorregiao (codestado, cod, nome) values ('35','15','Metropolitana de São Paulo');
insert into mesorregiao (codestado, cod, nome) values ('41','01','Noroeste Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','02','Centro Ocidental Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','03','Norte Central Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','04','Norte Pioneiro Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','05','Centro Oriental Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','06','Oeste Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','07','Sudoeste Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','08','Centro-Sul Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','09','Sudeste Paranaense');
insert into mesorregiao (codestado, cod, nome) values ('41','10','Metropolitana de Curitiba');
insert into mesorregiao (codestado, cod, nome) values ('42','01','Oeste Catarinense');
insert into mesorregiao (codestado, cod, nome) values ('42','02','Norte Catarinense');
insert into mesorregiao (codestado, cod, nome) values ('42','03','Serrana');
insert into mesorregiao (codestado, cod, nome) values ('42','04','Vale do Itajaí');
insert into mesorregiao (codestado, cod, nome) values ('42','05','Grande Florianópolis');
insert into mesorregiao (codestado, cod, nome) values ('42','06','Sul Catarinense');
insert into mesorregiao (codestado, cod, nome) values ('43','01','Noroeste Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('43','02','Nordeste Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('43','03','Centro Ocidental Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('43','04','Centro Oriental Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('43','05','Metropolitana de Porto Alegre');
insert into mesorregiao (codestado, cod, nome) values ('43','06','Sudoeste Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('43','07','Sudeste Rio-grandense');
insert into mesorregiao (codestado, cod, nome) values ('50','01','Pantanais Sul Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('50','02','Centro Norte de Mato Grosso do Sul');
insert into mesorregiao (codestado, cod, nome) values ('50','03','Leste de Mato Grosso do Sul');
insert into mesorregiao (codestado, cod, nome) values ('50','04','Sudoeste de Mato Grosso do Sul');
insert into mesorregiao (codestado, cod, nome) values ('51','01','Norte Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('51','02','Nordeste Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('51','03','Sudoeste Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('51','04','Centro-Sul Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('51','05','Sudeste Mato-grossense');
insert into mesorregiao (codestado, cod, nome) values ('52','01','Noroeste Goiano');
insert into mesorregiao (codestado, cod, nome) values ('52','02','Norte Goiano');
insert into mesorregiao (codestado, cod, nome) values ('52','03','Centro Goiano');
insert into mesorregiao (codestado, cod, nome) values ('52','04','Leste Goiano');
insert into mesorregiao (codestado, cod, nome) values ('52','05','Sul Goiano');
insert into mesorregiao (codestado, cod, nome) values ('53','01','Distrito Federal');
