insert into microrregiao (codestado, codmeso, cod, nome) values ('11','01','001',"Porto Velho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','01','002',"Guajará-Mirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('12','01','001',"Cruzeiro do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('12','01','002',"Tarauacá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','01','001',"Rio Negro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','01','002',"Japurá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('14','01','001',"Boa Vista");
insert into microrregiao (codestado, codmeso, cod, nome) values ('14','01','002',"Nordeste de Roraima");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','01','002',"Santarém");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','01','003',"Almeirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','01','001',"Óbidos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('16','01','002',"Amapá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('16','01','001',"Oiapoque");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','01','003',"Miracema do Tocantins");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','01','001',"Bico do Papagaio");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','01','005',"Gurupi");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','01','002',"Araguaína");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','01','004',"Rio Formoso");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','001',"Litoral Ocidental Maranhense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','005',"Baixada Maranhense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','003',"Rosário");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','004',"Lençóis Maranhenses");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','006',"Itapecuru Mirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','01','002',"Aglomeração Urbana de São Luís");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','01','001',"Baixo Parnaíba Piauiense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','01','002',"Litoral Piauiense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','001',"Litoral de Camocim e Acaraú");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','004',"Meruoca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','005',"Sobral");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','002',"Ibiapaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','007',"Santa Quitéria");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','003',"Coreaú");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','01','006',"Ipu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','004',"Vale do Açu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','005',"Serra de São Miguel");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','006',"Pau dos Ferros");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','007',"Umarizal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','002',"Chapada do Apodi");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','001',"Mossoró");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','01','003',"Médio Oeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','007',"Serra do Teixeira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','005',"Piancó");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','003',"Sousa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','004',"Patos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','001',"Catolé do Rocha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','002',"Cajazeiras");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','01','006',"Itaporanga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','01','003',"Pajeú");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','01','001',"Araripina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','01','004',"Sertão do Moxotó");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','01','002',"Salgueiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','01','001',"Serrana do Sertão Alagoano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','01','004',"Batalha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','01','003',"Santana do Ipanema");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','01','002',"Alagoana do Sertão do São Francisco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','01','001',"Sergipana do Sertão do São Francisco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','01','002',"Carira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','01','002',"Cotegipe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','01','001',"Barreiras");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','01','003',"Santa Maria da Vitória");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','01','001',"Unaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','01','002',"Paracatu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','01','001',"Barra de São Francisco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','01','002',"Nova Venécia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','01','003',"Colatina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','01','002',"Santo Antônio de Pádua");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','01','001',"Itaperuna");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','004',"São José do Rio Preto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','003',"Votuporanga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','001',"Jales");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','005',"Catanduva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','006',"Auriflama");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','002',"Fernandópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','008',"Novo Horizonte");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','01','007',"Nhandeara");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','01','002',"Umuarama");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','01','001',"Paranavaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','01','003',"Cianorte");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','01','003',"Xanxerê");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','01','004',"Joaçaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','01','002',"Chapecó");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','01','005',"Concórdia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','01','001',"São Miguel do Oeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','010',"Passo Fundo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','008',"Ijuí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','001',"Santa Rosa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','009',"Carazinho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','003',"Frederico Westphalen");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','011',"Cruz Alta");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','004',"Erechim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','002',"Três Passos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','005',"Sananduva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','013',"Soledade");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','007',"Santo Ângelo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','006',"Cerro Largo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','01','012',"Não-Me-Toque");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','01','002',"Aquidauana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','01','001',"Baixo Pantanal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','002',"Alta Floresta");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','001',"Aripuanã");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','004',"Parecis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','007',"Sinop");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','003',"Colíder");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','008',"Paranatinga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','006',"Alto Teles Pires");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','01','005',"Arinos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','01','003',"Aragarças");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','01','002',"Rio Vermelho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','01','001',"São Miguel do Araguaia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('53','01','001',"Brasília");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','006',"Cacoal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','003',"Ariquemes");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','005',"Alvorada D'Oeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','008',"Colorado do Oeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','007',"Vilhena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('11','02','004',"Ji-Paraná");
insert into microrregiao (codestado, codmeso, cod, nome) values ('12','02','004',"Rio Branco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('12','02','005',"Brasiléia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('12','02','003',"Sena Madureira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','02','003',"Alto Solimões");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','02','004',"Juruá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('14','02','003',"Caracaraí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('14','02','004',"Sudeste de Roraima");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','02','005',"Furos de Breves");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','02','004',"Portel");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','02','006',"Arari");
insert into microrregiao (codestado, codmeso, cod, nome) values ('16','02','003',"Macapá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('16','02','004',"Mazagão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','02','008',"Dianópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','02','006',"Porto Nacional");
insert into microrregiao (codestado, codmeso, cod, nome) values ('17','02','007',"Jalapão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','02','009',"Imperatriz");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','02','008',"Pindaré");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','02','007',"Gurupi");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','02','005',"Médio Parnaíba Piauiense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','02','004',"Campo Maior");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','02','003',"Teresina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','02','006',"Valença do Piauí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','013',"Baturité");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','008',"Itapipoca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','011',"Médio Curu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','014',"Chorozinho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','015',"Cascavel");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','012',"Canindé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','010',"Uruburetama");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','02','009',"Baixo Curu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','02','012',"Seridó Oriental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','02','009',"Angicos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','02','010',"Serra de Santana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','02','008',"Macau");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','02','011',"Seridó Ocidental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','02','011',"Cariri Oriental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','02','010',"Cariri Ocidental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','02','009',"Seridó Oriental Paraibano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','02','008',"Seridó Ocidental Paraibano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','02','005',"Petrolina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','02','006',"Itaparica");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','02','006',"Arapiraca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','02','005',"Palmeira dos Índios");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','02','007',"Traipu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','02','003',"Nossa Senhora das Dores");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','02','004',"Agreste de Itabaiana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','02','006',"Agreste de Lagarto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','02','005',"Tobias Barreto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','02','005',"Paulo Afonso");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','02','006',"Barra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','02','007',"Bom Jesus da Lapa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','02','004',"Juazeiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','005',"Salinas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','009',"Bocaiúva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','003',"Januária");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','008',"Grão Mogol");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','007',"Montes Claros");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','006',"Pirapora");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','02','004',"Janaúba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','02','006',"Linhares");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','02','005',"São Mateus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','02','004',"Montanha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','02','003',"Campos dos Goytacazes");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','02','004',"Macaé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','015',"Batatais");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','011',"Ituverava");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','009',"Barretos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','014',"Ribeirão Preto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','013',"Jaboticabal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','012',"Franca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','02','010',"São Joaquim da Barra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','02','004',"Goioerê");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','02','005',"Campo Mourão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','02','008',"Joinville");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','02','006',"Canoinhas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','02','007',"São Bento do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','02','014',"Guaporé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','02','016',"Caxias do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','02','015',"Vacaria");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','02','003',"Alto Taquari");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','02','004',"Campo Grande");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','02','010',"Canarana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','02','009',"Norte Araguaia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','02','011',"Médio Araguaia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','02','004',"Porangatu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','02','005',"Chapada dos Veadeiros");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','005',"Tefé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','006',"Coari");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','007',"Manaus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','010',"Parintins");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','009',"Itacoatiara");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','03','008',"Rio Preto da Eva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','03','007',"Belém");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','03','008',"Castanhal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','03','011',"Alto Mearim e Grajaú");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','03','010',"Médio Mearim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','03','012',"Presidente Dutra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','010',"Alto Médio Gurguéia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','011',"São Raimundo Nonato");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','008',"Bertolínia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','012',"Chapadas do Extremo Sul Piauiense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','007',"Alto Parnaíba Piauiense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','03','009',"Floriano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','03','016',"Fortaleza");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','03','017',"Pacajus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','03','014',"Borborema Potiguar");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','03','013',"Baixa Verde");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','03','015',"Agreste Potiguar");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','015',"Brejo Paraibano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','016',"Guarabira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','012',"Curimataú Ocidental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','013',"Curimataú Oriental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','014',"Esperança");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','019',"Umbuzeiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','017',"Campina Grande");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','03','018',"Itabaiana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','012',"Brejo Pernambucano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','007',"Vale do Ipanema");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','008',"Vale do Ipojuca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','011',"Garanhuns");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','010',"Médio Capibaribe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','03','009',"Alto Capibaribe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','012',"São Miguel dos Campos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','009',"Mata Alagoana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','011',"Maceió");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','008',"Serrana dos Quilombos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','013',"Penedo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('27','03','010',"Litoral Norte Alagoano");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','007',"Propriá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','011',"Aracaju");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','012',"Boquim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','008',"Cotinguiba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','010',"Baixo Cotinguiba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','013',"Estância");
insert into microrregiao (codestado, codmeso, cod, nome) values ('28','03','009',"Japaratuba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','03','012',"Feira de Santana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','03','009',"Irecê");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','03','008',"Senhor do Bonfim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','03','011',"Itaberaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','03','010',"Jacobina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','03','014',"Almenara");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','03','011',"Capelinha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','03','012',"Araçuaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','03','013',"Pedra Azul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','03','010',"Diamantina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','03','007',"Afonso Cláudio");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','03','010',"Guarapari");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','03','009',"Vitória");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','03','008',"Santa Teresa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','03','005',"Três Rios");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','03','007',"Nova Friburgo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','03','006',"Cantagalo-Cordeiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','03','008',"Santa Maria Madalena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','03','018',"Birigui");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','03','016',"Andradina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','03','017',"Araçatuba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','007',"Porecatu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','006',"Astorga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','010',"Apucarana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','013',"Ivaiporã");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','012',"Faxinal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','011',"Londrina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','008',"Floraí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','03','009',"Maringá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','03','009',"Curitibanos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','03','010',"Campos de Lages");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','03','019',"Restinga Seca");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','03','018',"Santa Maria");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','03','017',"Santiago");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','03','007',"Três Lagoas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','03','008',"Nova Andradina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','03','006',"Paranaíba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','03','005',"Cassilândia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','03','014',"Jauru");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','03','013',"Tangará da Serra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','03','012',"Alto Guaporé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','03','010',"Goiânia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','03','009',"Anicuns");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','03','008',"Iporá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','03','007',"Anápolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','03','006',"Ceres");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','04','013',"Madeira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','04','011',"Boca do Acre");
insert into microrregiao (codestado, codmeso, cod, nome) values ('13','04','012',"Purus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','04','011',"Cametá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','04','012',"Tomé-Açu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','04','010',"Bragantina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','04','013',"Guamá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','04','009',"Salgado");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','016',"Coelho Neto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','013',"Baixo Parnaíba Maranhense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','015',"Codó");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','014',"Chapadinha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','018',"Chapadas do Alto Itapecuru");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','04','017',"Caxias");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','04','015',"Alto Médio Canindé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','04','014',"Pio IX");
insert into microrregiao (codestado, codmeso, cod, nome) values ('22','04','013',"Picos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','04','021',"Sertão de Senador Pompeu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','04','020',"Sertão de Inhamuns");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','04','018',"Sertão de Cratéus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','04','019',"Sertão de Quixeramobim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','04','019',"Litoral Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','04','017',"Macaíba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','04','018',"Natal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('24','04','016',"Litoral Nordeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','04','023',"Litoral Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','04','020',"Litoral Norte");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','04','022',"João Pessoa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('25','04','021',"Sapé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','04','015',"Mata Meridional Pernambucana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','04','013',"Mata Setentrional Pernambucana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','04','014',"Vitória de Santo Antão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','017',"Alagoinhas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','015',"Ribeira do Pombal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','016',"Serrinha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','014',"Euclides da Cunha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','018',"Entre Rios");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','04','013',"Jeremoabo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','04','016',"Nanuque");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','04','015',"Teófilo Otoni");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','04','011',"Alegre");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','04','012',"Cachoeiro de Itapemirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('32','04','013',"Itapemirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','04','010',"Lagos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','04','009',"Bacia de São João");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','04','022',"Avaré");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','04','020',"Bauru");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','04','023',"Botucatu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','04','021',"Jaú");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','04','019',"Lins");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','04','015',"Cornélio Procópio");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','04','014',"Assaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','04','016',"Jacarezinho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','04','018',"Wenceslau Braz");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','04','017',"Ibaiti");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','04','014',"Ituporanga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','04','011',"Rio do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','04','012',"Blumenau");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','04','013',"Itajaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','04','021',"Lajeado-Estrela");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','04','020',"Santa Cruz do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','04','022',"Cachoeira do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','04','010',"Dourados");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','04','011',"Iguatemi");
insert into microrregiao (codestado, codmeso, cod, nome) values ('50','04','009',"Bodoquena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','04','016',"Rosário Oeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','04','015',"Alto Paraguai");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','04','018',"Alto Pantanal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','04','017',"Cuiabá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','04','012',"Entorno de Brasília");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','04','011',"Vão do Paranã");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','05','015',"Altamira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','05','014',"Itaituba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','05','020',"Gerais de Balsas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','05','021',"Chapadas das Mangabeiras");
insert into microrregiao (codestado, codmeso, cod, nome) values ('21','05','019',"Porto Franco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','05','023',"Baixo Jaguaribe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','05','022',"Litoral de Aracati");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','05','025',"Serra do Pereiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','05','024',"Médio Jaguaribe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','05','017',"Recife");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','05','016',"Itamaracá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','05','018',"Suape");
insert into microrregiao (codestado, codmeso, cod, nome) values ('26','05','019',"Fernando de Noronha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','05','019',"Catu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','05','020',"Santo Antônio de Jesus");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','05','021',"Salvador");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','019',"Patrocínio");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','022',"Uberaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','018',"Uberlândia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','020',"Patos de Minas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','023',"Araxá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','017',"Ituiutaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','05','021',"Frutal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','05','013',"Baía da Ilha Grande");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','05','012',"Barra do Piraí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','05','011',"Vale do Paraíba Fluminense");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','05','024',"Araraquara");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','05','025',"São Carlos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','05','020',"Jaguariaíva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','05','021',"Ponta Grossa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','05','019',"Telêmaco Borba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','05','017',"Tabuleiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','05','015',"Tijucas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','05','016',"Florianópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','023',"Montenegro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','026',"Porto Alegre");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','028',"Camaquã");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','027',"Osório");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','025',"São Jerônimo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','05','024',"Gramado-Canela");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','05','022',"Alto Araguaia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','05','020',"Tesouro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','05','019',"Primavera do Leste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('51','05','021',"Rondonópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','014',"Vale do Rio dos Bois");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','015',"Meia Ponte");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','017',"Catalão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','013',"Sudoeste de Goiás");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','018',"Quirinópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('52','05','016',"Pires do Rio");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','017',"Paragominas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','019',"Parauapebas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','018',"São Félix do Xingu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','020',"Marabá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','016',"Tucuruí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','022',"Conceição do Araguaia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('15','06','021',"Redenção");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','06','027',"Várzea Alegre");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','06','028',"Lavras da Mangabeira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','06','026',"Iguatu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','023',"Seabra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','024',"Jequié");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','028',"Vitória da Conquista");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','027',"Brumado");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','022',"Boquira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','026',"Guanambi");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','025',"Livramento do Brumado");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','06','029',"Itapetinga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','06','024',"Três Marias");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','06','026',"Bom Despacho");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','06','025',"Curvelo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','06','018',"Rio de Janeiro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','06','016',"Macacu-Caceribu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','06','014',"Vassouras");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','06','017',"Itaguaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('33','06','015',"Serrana");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','06','028',"Piracicaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','06','027',"Limeira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','06','026',"Rio Claro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','06','023',"Cascavel");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','06','022',"Toledo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','06','024',"Foz do Iguaçu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','06','020',"Araranguá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','06','018',"Tubarão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('42','06','019',"Criciúma");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','06','031',"Campanha Meridional");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','06','029',"Campanha Ocidental");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','06','030',"Campanha Central");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','07','033',"Brejo Santo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','07','030',"Caririaçu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','07','029',"Chapada do Araripe");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','07','031',"Barro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('23','07','032',"Cariri");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','07','032',"Porto Seguro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','07','031',"Ilhéus-Itabuna");
insert into microrregiao (codestado, codmeso, cod, nome) values ('29','07','030',"Valença");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','031',"Itabira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','028',"Conceição do Mato Dentro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','027',"Sete Lagoas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','030',"Belo Horizonte");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','032',"Itaguara");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','034',"Conselheiro Lafaiete");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','033',"Ouro Preto");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','07','029',"Pará de Minas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','07','029',"Pirassununga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','07','030',"São João da Boa Vista");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','07','033',"Amparo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','07','032',"Campinas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','07','031',"Mogi Mirim");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','07','025',"Capanema");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','07','026',"Francisco Beltrão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','07','027',"Pato Branco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','07','032',"Serras de Sudeste");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','07','033',"Pelotas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','07','034',"Jaguarão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('43','07','035',"Litoral Lagunar");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','039',"Ipatinga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','036',"Peçanha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','041',"Aimorés");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','037',"Governador Valadares");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','040',"Caratinga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','035',"Guanhães");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','08','038',"Mantena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','08','035',"Adamantina");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','08','036',"Presidente Prudente");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','08','034',"Dracena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','08','028',"Pitanga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','08','029',"Guarapuava");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','08','030',"Palmas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','09','045',"Campo Belo");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','09','044',"Formiga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','09','042',"Piuí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','09','046',"Oliveira");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','09','043',"Divinópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','09','038',"Marília");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','09','037',"Tupã");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','09','034',"São Mateus do Sul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','09','033',"União da Vitória");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','09','031',"Prudentópolis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','09','032',"Irati");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','055',"Andrelândia");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','054',"São Lourenço");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','051',"Poços de Caldas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','049',"Alfenas");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','047',"Passos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','048',"São Sebastião do Paraíso");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','050',"Varginha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','052',"Pouso Alegre");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','056',"Itajubá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','10','053',"Santa Rita do Sapucaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','10','039',"Assis");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','10','040',"Ourinhos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','10','035',"Cerro Azul");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','10','039',"Rio Negro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','10','037',"Curitiba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','10','038',"Paranaguá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('41','10','036',"Lapa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','11','059',"Barbacena");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','11','057',"Lavras");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','11','058',"São João Del Rei");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','11','042',"Itapetininga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','11','044',"Capão Bonito");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','11','041',"Itapeva");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','11','043',"Tatuí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','061',"Manhuaçu");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','060',"Ponte Nova");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','066',"Cataguases");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','062',"Viçosa");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','063',"Muriaé");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','065',"Juiz de Fora");
insert into microrregiao (codestado, codmeso, cod, nome) values ('31','12','064',"Ubá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','12','046',"Sorocaba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','12','048',"Bragança Paulista");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','12','047',"Jundiaí");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','12','045',"Piedade");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','051',"Guaratinguetá");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','052',"Bananal");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','050',"São José dos Campos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','049',"Campos do Jordão");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','054',"Caraguatatuba");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','13','053',"Paraibuna/Paraitinga");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','14','055',"Registro");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','14','056',"Itanhaém");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','059',"Guarulhos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','057',"Osasco");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','063',"Santos");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','062',"Mogi das Cruzes");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','058',"Franco da Rocha");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','060',"Itapecerica da Serra");
insert into microrregiao (codestado, codmeso, cod, nome) values ('35','15','061',"São Paulo");
